Demo Compas App/Models/UserMaster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Compas_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserMaster
    {
        [Key]
        public int UserId { get; set; }
        public string UserFname { get; set; }
        public string UserLname { get; set; }
        [DisplayName("User Name")]
        public string UserName { get; set; }
        [DisplayName("Password")]
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> UserContactno { get; set; }
        [DisplayName("Role Name")]
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> isActive { get; set; }

        public virtual RoleMaster RoleMaster { get; set; }
        [NotMapped]
        public List<RoleMaster> RoleCollection { get; set; }
        public string Loginerror { get; set; }
    }
}

Demo Compas App/Controllers/UserMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Demo_Compas_App.Models;
using System.Data;
namespace Demo_Compas_App.Controllers
{
    public class UserMasterController : Controller
    {
        public EntityState EntiyState { get; private set; }
        // GET: UserMaster
        public ActionResult Users()
        {
            using (ProjectMasterEntities dbModel = new ProjectMasterEntities()) 
            {

                return View(dbModel.UserMasters.ToList());
            }

                
        }

        // GET: UserMaster/Details/5
        public ActionResult Details(int id)
        {
            using (ProjectMasterEntities dbModel = new ProjectMasterEntities())
            {
                return View(dbModel.UserMasters.Where(x =>x.UserId==id).FirstOrDefault());

            }
                
        }

        // GET: UserMaster/Create
        public ActionResult Create(int id=0)
        {
            UserMaster usermodel = new UserMaster();
            using (ProjectMasterEntities db = new ProjectMasterEntities())
            {
                usermodel.RoleCollection = db.RoleMasters.ToList<RoleMaster>();
            }
                return View(usermodel);
        }

        // POST: UserMaster/Create
        [HttpPost]
        public ActionResult Create(UserMaster usermaster)
        {
            try
            {
                
                
                    using (ProjectMasterEntities dbModel = new ProjectMasterEntities())
                    {
                        dbModel.UserMasters.Add(usermaster);
                        dbModel.SaveChanges();

                }
                return RedirectToAction("Index");
            }
             
            catch(Exception ex)
            {
                
                return View();
            }
        }

        // GET: UserMaster/Edit/5
        public ActionResult Edit(int id=0)
        {
            //UserMaster usermodel = new UserMaster();
           // using (UserMasterEntities dbModel = new UserMasterEntities())
           //{
               
           //     //usermodel.RoleCollection = dbModel.RoleMasters.ToList<RoleMaster>();
           //     return View(dbModel.UserMasters.Where(x => x.UserId == id).FirstOrDefault());
           // }
            //return View(usermodel);


            UserMaster usermodel = new UserMaster();
            using (ProjectMasterEntities db = new ProjectMasterEntities())
            {
                usermodel = db.UserMasters.Where(x => x.UserId == id).FirstOrDefault();
                usermodel.RoleCollection = db.RoleMasters.ToList<RoleMaster>();
            }
            return View(usermodel);


        }

        // POST: UserMaster/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, UserMaster usermaster)
        {
            try
            {
                using (ProjectMasterEntities dbModel = new ProjectMasterEntities())
                {
                    dbModel.Entry(usermaster).State = EntityState.Modified;
                    dbModel.SaveChanges();
                }
                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserMaster/Delete/5
        public ActionResult Delete(int id)
        {
            using (ProjectMasterEntities dbModel = new ProjectMasterEntities())
            {
                return View(dbModel.UserMasters.Where(x => x.UserId == id).FirstOrDefault());
            }
        }

        // POST: UserMaster/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (ProjectMasterEntities dbModel = new ProjectMasterEntities())
                {
                    UserMaster usermaster = dbModel.UserMasters.Where(x => x.UserId == id).FirstOrDefault();
                    dbModel.UserMasters.Remove(usermaster);
                    dbModel.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Demo Compas App/Views/UserMaster/Create.cshtml
@model Demo_Compas_App.Models.UserMaster

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","UserMaster",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User Master</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--    <div class="form-group">
                @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div> -->

        <div class="form-group">
            @Html.LabelFor(model => model.UserFname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserFname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserFname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserLname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserLname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserLname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserContactno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserContactno, new { htmlAttributes = new { @class = "form-control" } })
                <span style="color:red">Office 5 Digit Number</span>
                @Html.ValidationMessageFor(model => model.UserContactno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                @Html.DropDownListFor(model => model.RoleId,new SelectList(Model.RoleCollection,"RoleId","RoleName"),"--Select Role--")
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
      </div>
        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })

            <label>
                @Html.RadioButtonFor(model => model.isActive, true)
                Active
            </label>

            <label>
                @Html.RadioButtonFor(model => model.isActive, false )
                Inactive
            </label>

            <div class="col-md-10">

                @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <input type="reset" value="Clear" class="btn btn-default" />
            </div>
        </div>
    </div>
 }

<div>
    @Html.ActionLink("Back to List", "Users")
</div>

Demo Compas App/Views/UserMaster/Delete.cshtml
@model Demo_Compas_App.Models.UserMaster

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<style>
    td, th {
        border: 1px,solid,black;
        text-align: center;
        padding: 5px;
    }
</style>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User Master</h4>
    <hr />
    <table border="1" align="center">
        <tr>
            <th>@Html.DisplayNameFor(model => model.UserId)</th>
            <th>@Html.DisplayNameFor(model => model.UserFname)</th>
            <th>@Html.DisplayNameFor(model => model.UserLname)</th>
            <th>@Html.DisplayNameFor(model => model.UserName)</th>
            <th>@Html.DisplayNameFor(model => model.UserPassword)</th>
            <th>@Html.DisplayNameFor(model => model.UserEmail)</th>
            <th>@Html.DisplayNameFor(model => model.UserContactno)</th>
            <th>@Html.DisplayNameFor(model => model.RoleId)</th>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.UserId)</td>
            <td>@Html.DisplayFor(model => model.UserFname)</td>
            <td>@Html.DisplayFor(model => model.UserLname)</td>
            <td>@Html.DisplayFor(model => model.UserName)</td>
            <td>@Html.DisplayFor(model => model.UserPassword)</td>
            <td>@Html.DisplayFor(model => model.UserEmail)</td>
            <td>@Html.DisplayFor(model => model.UserContactno)</td>
            <td>@Html.DisplayFor(model => model.RoleId)</td>

        </tr>
    </table>
 <br />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="text-align:center">
            <input type="submit" value="Delete" class="btn btn-default"  /> 
           
        </div>
        @Html.ActionLink("Back to List", "Index")
    }
</div>

Demo Compas App/Views/UserMaster/Details.cshtml
@model Demo_Compas_App.Models.UserMaster

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<style>
    td, th {
        border: 1px,solid,black;
        text-align: center;
        padding: 5px;
    }
</style>
<div>
    <h4>UserMaster</h4>
    <hr />
    <table border="1" align="center">
        <tr>
            <th>@Html.DisplayNameFor(model => model.UserId)</th>
            <th>@Html.DisplayNameFor(model => model.UserFname)</th>
            <th>@Html.DisplayNameFor(model => model.UserLname)</th>
            <th>@Html.DisplayNameFor(model => model.UserName)</th>
            <th>@Html.DisplayNameFor(model => model.UserPassword)</th>
            <th>@Html.DisplayNameFor(model => model.UserEmail)</th>
            <th>@Html.DisplayNameFor(model => model.UserContactno)</th>
            <th>@Html.DisplayNameFor(model => model.RoleId)</th>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.UserId)</td>
            <td>@Html.DisplayFor(model => model.UserFname)</td>
            <td>@Html.DisplayFor(model => model.UserLname)</td>
            <td>@Html.DisplayFor(model => model.UserName)</td>
            <td>@Html.DisplayFor(model => model.UserPassword)</td>
            <td>@Html.DisplayFor(model => model.UserEmail)</td>
            <td>@Html.DisplayFor(model => model.UserContactno)</td>
            <td>@Html.DisplayFor(model => model.RoleId)</td>

        </tr>
        </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Demo Compas App/Views/UserMaster/Edit.cshtml
@model Demo_Compas_App.Models.UserMaster

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserMaster</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserFname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserFname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserFname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserLname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserLname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserLname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserContactno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserContactno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserContactno, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoleId, new SelectList(Model.RoleCollection, "RoleId", "RoleName"), "--Select Role--")
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>

                         
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <input type="reset" value="Clear" class="btn btn-default"/>
            </div>
        </div>
    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Demo Compas App/Views/UserMaster/Index.cshtml
@model IEnumerable<Demo_Compas_App.Models.UserMaster>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserFname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserLname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserContactno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserFname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserLname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserPassword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserContactno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new {  id=item.UserId  }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
        </td>
    </tr>
}

</table>

Demo Compas App/Views/UserMaster/Users.cshtml
@model IEnumerable<Demo_Compas_App.Models.UserMaster>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserFname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserLname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserPassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserContactno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserFname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserLname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserPassword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserContactno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new {  id=item.UserId  }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
        </td>
    </tr>
}

</table>